version: "3"

services:
  jupyterhub:
    restart: always
    build:
      context: ./
      dockerfile: ./minimal-jupyterhub-example/jupyterhub/Dockerfile
    hostname: jupyterhub
    env_file:
      - ./minimal-jupyterhub-example/couchdb_credentials.env
    ports:
      - "8000:8000"
  couchdb:
    restart: always
    build: ./minimal-jupyterhub-example/couchdb/
    hostname: couchdb
    env_file:
      - ./minimal-jupyterhub-example/couchdb_credentials.env
    ports:
    - "6984:6984"
